## Regresion lineal
#### Usando scikit-learn para regresion lineal y la seleccion de rasgos

In [3]:
from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np

In [4]:
data = pd.read_csv('https://raw.githubusercontent.com/joanby/python-ml-course/master/datasets/ads/Advertising.csv')

In [5]:
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [6]:
feature_cols = ['TV','Radio','Newspaper']

In [8]:
x = data[feature_cols]
y = data['Sales']

In [10]:
estimator = SVR(kernel='linear')
selector = RFE(estimator,2, step=1)
selector = selector.fit(x,y)

In [11]:
selector.support_

array([ True,  True, False])

In [12]:
selector.ranking_

array([1, 1, 2])

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
predictore_cols=['TV','Radio']

In [15]:
x = data [predictore_cols]

In [20]:
lm = LinearRegression()

In [22]:
lm.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [23]:
lm.intercept_

2.921099912405138

In [24]:
lm.coef_

array([0.04575482, 0.18799423])

In [25]:
lm.score(x,y)

0.8971942610828956